name: Credit Card Fraud Detection Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install imbalanced-learn scikit-learn

    - name: Authenticate via Google Cloud CLI
      run: |
        # Tự động tạo file json từ secret một cách an toàn nhất trong bash
        echo '${{ secrets.GCP_CREDENTIALS }}' > gcp_key.json
        
        # Kích hoạt xác thực gcloud trực tiếp
        gcloud auth activate-service-account --key-file=gcp_key.json
        gcloud config set project frauddetection-507910

    - name: Run Fraud Detection Pipeline
      run: |
        python src/data_engineer.py
      env:
        PYTHONPATH: src
        # Trỏ thẳng đường dẫn đến file key vừa tạo bằng tay
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
